# frozen_string_literal: true

source 'https://rubygems.org'

gem 'coderay',   '~> 1.1.1'
gem 'rack-test', '~> 0.7.0'
gem 'rspec',     '~> 3.6.0'
gem 'sinatra',   '~> 2.0.2'
gem 'pry',       '~> 0.11.0'
